name: Build & Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/checkout@v4
        if: ${{ steps.release-please.outputs.release_created }}
      - uses: actions/setup-go@v4
        if: ${{ steps.release-please.outputs.release_created }}
        with:
          go-version: 1.25
      - name: Build
        if: ${{ steps.release-please.outputs.release_created }}
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: 1.25.x
          pkg: cmd/scraper/
          dest: build
          prefix: annscraper
          targets: linux/amd64,darwin/amd64,darwin/arm64,windows/amd64,
          v: true
          ldflags: -s -w
      - name: Upload Release Binaries
        if: ${{ steps.release-please.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release-please.outputs.tag_name }} ./build/*
